In [4]:
import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [8]:
FILE_PATH = "../data/supply_chain_datasheet.xlsx"

excel = pd.ExcelFile(FILE_PATH)

excel.sheet_names

['READ ME',
 'A - Plants & Production',
 'B - Plant-Hub Transport',
 'C -Hub-CFA Transport',
 'D -SKU Portfolio+Penalty matrix',
 'E - Source + LT data',
 'F - Service Levels',
 'G - Sales History',
 'H - Forecast History',
 'I - Expected opening Inventory',
 'J - Jan Forecast']

In [10]:
plants_raw = pd.read_excel(
    FILE_PATH,
    sheet_name="A - Plants & Production",
    header=None
)

plants_raw

,0,1,2,3,4,5,6,7,8
0,EXHIBIT A — Plant Production Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Plant Code,Location,State / Region,Line Capacity \n<=1.5 LT (kl / month),Line Capacity \n3- 5 LT (kl / month),Line Capacity \n7- 20 LT (kl / month),Line Capacity \n50 LT (kl / month),Line Capacity \n180- 210LT (kl / month),Production Cost (₹/kl)
3,BOM,Mumbai,Maharashtra — West India,1200,900,1000,0,2450,12000
4,AHM,Ahmedabad,Gujarat — West India,1600,550,1000,220,2200,12500
5,KOL,Kolkata,West Bengal — East India,1200,500,650,0,200,9000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,All production volumes must be integer multipl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
for sheet in excel.sheet_names:
    print("=" * 80)
    print(sheet)

    df = pd.read_excel(FILE_PATH, sheet_name=sheet, header=None)

    print(f"Shape: {df.shape}")

    display(df.head(8))

================================================================================
READ ME
Shape: (16, 2)

    0                                                  1
0 NaN                SUPPLY CHAIN CASE STUDY — DATA FILE
1 NaN                                                NaN
2 NaN  This file contains all input data for the Levi...
3 NaN                                                NaN
4 NaN                                             Sheets
5 NaN                            A - Plants & Production
6 NaN                           B - Hub-to-Hub Transport
7 NaN                           C - Hub-to-CFA Transport

================================================================================
A - Plants & Production
Shape: (8, 9)

,0,1,2,3,4,5,6,7,8
0,EXHIBIT A — Plant Production Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Plant Code,Location,State / Region,Line Capacity \n<=1.5 LT (kl / month),Line Capacity \n3- 5 LT (kl / month),Line Capacity \n7- 20 LT (kl / month),Line Capacity \n50 LT (kl / month),Line Capacity \n180- 210LT (kl / month),Production Cost (₹/kl)
3,BOM,Mumbai,Maharashtra — West India,1200,900,1000,0,2450,12000
4,AHM,Ahmedabad,Gujarat — West India,1600,550,1000,220,2200,12500
5,KOL,Kolkata,West Bengal — East India,1200,500,650,0,200,9000
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,All production volumes must be integer multipl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

================================================================================
B - Plant-Hub Transport
Shape: (8, 3)

,0,1,2
0,EXHIBIT B — Plant to Hub Transport Costs (₹ pe...,NaN,NaN
1,NaN,NaN,NaN
2,From Plant,To Mother Hub West (MHW),To Mother Hub East (MHE)
3,Mumbai,1000,8000
4,Ahmedabad,4000,5000
5,Kolkata,10000,1100
6,NaN,NaN,NaN
7,Any plant may supply any hub. There is no hard...,NaN,NaN

================================================================================
C -Hub-CFA Transport
Shape: (15, 4)

,0,1,2,3
0,EXHIBIT C — Hub to CFA Transport Costs (₹ per kl),NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,CFA,Region,From Mother Hub West (MHW),From Mother Hub East (MHE)
3,Guwahati,East,7800,4200
4,Kolkata,East,8000,1100
5,Jamshedpur,East,5100,1700
6,Kanpur,North,3800,3100
7,Haryana,North,4400,4500

================================================================================
D -SKU Portfolio+Penalty matrix
Shape: (103, 4)

,0,1,2,3
0,EXHIBIT D — SKU Portfolio: Penalty cost and Co...,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Product Name,Pack size,Penalty cost (per kL),Contractual?
3,SKU_001,20 X 900 ML,220000,No
4,SKU_002,20 X 1 LT,180000,No
5,SKU_003,20 X 900 ML,230000,No
6,SKU_004,12 X 800 ML,140000,No
7,SKU_005,1 X 7.5 LT,230000,No

================================================================================
E - Source + LT data
Shape: (960, 10)

,0,1,2,3,4,5,6,7,8,9
0,EXHIBIT E — Historical Southrcing matrix +LT m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Product Name,Pack size,CFA region,CFA,Source,LT (Plant to Hub)(in days),LT (Hub to CFA ) (in days),Production lead time (in days),Production variability (in days),Transit lead variability (in days)
3,SKU_001,20 X 900 ML,East,Kolkata CFA,East,1,1,1,0,1
4,SKU_001,20 X 900 ML,East,Guwahati CFA,East,1,4,1,0,2
5,SKU_001,20 X 900 ML,East,Kanpur CFA,East,1,4,1,0,2
6,SKU_001,20 X 900 ML,East,Jamshedpur CFA,East,1,2,1,0,1
7,SKU_001,20 X 900 ML,North,Rajpura CFA,Rest of India,1,4,1,0,2

================================================================================
F - Service Levels
Shape: (9, 4)

,0,1,2,3
0,EXHIBIT G — Target Service Levels by SKU Tier,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN
2,Tier,Description,Volume contribution (%),Target Fill Rate (%)
3,A,Highest volume — flagship brands and top-selli...,0.5,98%
4,B,High-volume commercial products,0.3,97%
5,C,Mid-volume products,0.15,92%
6,D,Lower-volume / speciality products,0.05,92%
7,NaN,NaN,NaN,NaN

================================================================================
G - Sales History
Shape: (960, 10)

,0,1,2,3,4,5,6,7,8,9
0,EXHIBIT H — Monthly Actual Sales (kl) by SKU ×...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Product Name,Pack size,CFA region,CFA,Jul-25 (in kL),Aug-25 (in kL),Sep-25 (in kL),Oct-25 (in kL),Nov-25 (in kL),Dec-25 (in kL)
3,SKU_001,20 X 900 ML,East,Kolkata CFA,119.50128,133.8588,139.74912,119.2068,112.3884,131.44608
4,SKU_001,20 X 900 ML,East,Guwahati CFA,11.42496,15.88968,16.00056,8.71344,8.23968,15.88248
5,SKU_001,20 X 900 ML,East,Kanpur CFA,321.32448,344.79504,354.55392,344.7972,322.90632,420.60384
6,SKU_001,20 X 900 ML,East,Jamshedpur CFA,34.0272,42.64056,52.05456,43.55352,29.87208,34.09344
7,SKU_001,20 X 900 ML,North,Rajpura CFA,56.91096,45.62928,52.10352,52.95888,35.58312,46.72584

================================================================================
H - Forecast History
Shape: (961, 10)

,0,1,2,3,4,5,6,7,8,9
0,EXHIBIT I — Monthly Forecasts (kl) by SKU × CF...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Forecasts are generated by the demand planning...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Product Name,Pack size,CFA region,CFA,Jul-25 (in kL),Aug-25 (in kL),Sep-25 (in kL),Oct-25 (in kL),Nov-25 (in kL),Dec-25 (in kL)
4,SKU_001,20 X 900 ML,East,Kolkata CFA,121.765126,150.885844,146.032757,148.560885,110.288806,132.14905
5,SKU_001,20 X 900 ML,East,Guwahati CFA,11.627152,14.407281,13.943814,14.185289,12.517985,14.051793
6,SKU_001,20 X 900 ML,East,Kanpur CFA,277.191409,343.128105,347.566532,348.914688,353.269737,344.63547
7,SKU_001,20 X 900 ML,East,Jamshedpur CFA,45.172751,55.858718,52.99968,53.917515,43.093155,45.326792

================================================================================
I - Expected opening Inventory
Shape: (1112, 5)

,0,1,2,3,4
0,EXHIBIT J — Opening Inventory (kl) by SKU × CF...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Product Name,Pack size,CFA region,CFA,Jan -2026 (in kL)
4,SKU_001,20 X 900 ML,East,Kolkata CFA,17.98488
5,SKU_001,20 X 900 ML,East,Guwahati CFA,3.8592
6,SKU_001,20 X 900 ML,East,Kanpur CFA,40.176
7,SKU_001,20 X 900 ML,East,Jamshedpur CFA,19.49256

================================================================================
J - Jan Forecast
Shape: (961, 5)

,0,1,2,3,4
0,EXHIBIT J — January 2026 Forecast (kl) by SKU ...,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,Product Name,Pack size,CFA region,CFA,Jan -2026 (in kL)
4,SKU_001,20 X 900 ML,East,Kolkata CFA,191.73893
5,SKU_001,20 X 900 ML,East,Guwahati CFA,24.072936
6,SKU_001,20 X 900 ML,East,Kanpur CFA,248.529854
7,SKU_001,20 X 900 ML,East,Jamshedpur CFA,43.438783